version: '3.7'

services:
  php71:
    build:
      context: ./
      dockerfile: docker/php71/Dockerfile
    volumes:
      - ./laravel:/var/www
    working_dir: /var/www
    networks:
      - default

### MongoDB ##############################################
  mongo:
    image: mongo:4.2
    ports:
      - "27017:27017"
    networks:
      - default

### Redis ################################################
  redis:
    image: redis:5
    ports:
      - "6379:6379"
    networks:
      - default

### Nginx ################################################
  nginx:
    image: nginx:1.19
    links:
      - php71
    ports:
      - '8071:8071'
    depends_on:
      - php71
    volumes:
      - ./laravel:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
      - NET_BIND_SERVICE
    # security_opt:
    networks:
      - default
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
